module.exports = {
  VEEDGEE: {
    API_BASE_URL: process.env.VEEDGEE_API_BASE_URL,
    API_TOKEN: process.env.VEEDGEE_API_TOKEN,
    WORKER_TOKENS: process.env.VEEDGEE_WORKER_TOKENS
  },
  NOTIFICATION_SENDER: process.env.VEEDGEE_WORKERS_NOTIFICATION_SENDER,
  NOTIFICATION_RECIPIENTS: process.env.VEEDGEE_WORKERS_NOTIFICATION_RECIPIENTS,
  RESEND_API_TOKEN: process.env.VEEDGEE_WORKERS_RESEND_API_TOKEN,
  BUGSNAG_API_TOKEN: process.env.BUGSNAG_API_TOKEN,
  HUGGING_FACE_API_TOKEN: process.env.HUGGING_FACE_API_TOKEN,
  RAPID_API_TOKEN: process.env.RAPID_API_TOKEN
};
