module.exports = {
  VEEDGEE: {
    API_BASE_URL: process.env.VEEDGEE_API_BASE_URL,
    API_TOKEN: process.env.VEEDGEE_API_TOKEN
  },
  NOTIFICATION_SENDER: process.env.VEEDGEE_WORKERS_NOTIFICATION_SENDER,
  NOTIFICATION_RECIPIENTS: process.env.VEEDGEE_WORKERS_NOTIFICATION_RECIPIENTS,
  RESEND_API_TOKEN: process.env.VEEDGEE_WORKERS_RESEND_API_TOKEN
};
